### ISSUE TITLE
maybe a typo

### ISSUE THREAD

**Issue by ericlin1001** [MarkLodato/visual-git-guide#48]
In section about ```reset```, the ariticle wrote ```'If a **commit** is given with no filenames, the current branch is moved to that commit...'````,  the first commit should be reset, right?

**Comment by MarkLodato** [comment]
What I meant is that "if a reset command is given with a commit but no filenames on the command line", e.g. `git reset a235fb` as opposed to `git reset` or `git reset some_file.txt`.

**Comment by ericlin1001** [comment]
Ok~
