### ISSUE TITLE
Add `git clean` section to show how to remove untracked files

### ISSUE THREAD

**Issue by activedecay** [MarkLodato/visual-git-guide#52]
There's no visual reference for untracked files.

Add `git clean` section to show how to remove untracked files.

**Comment by MarkLodato** [comment]
I'm not so sure this really fits with the purpose of the doc. My goal is not to explain every git command but rather to present a mental model of how git works. To me, `git clean` is just one of several hundred commands that are useful on occasion but are not critical in every day use.

**Comment by activedecay** [comment]
Cool, I like that it's focused on every tasks. The command `git clean` is a fancy `rm` anyway. 

Suzanna of other commands!?! I have more reading to do; your visual reference got me this far. Really appreciate.

**Comment by activedecay** [comment]
i need this command again, and forgot about what it was. i may just fork this project.
