### ISSUE TITLE
Consider renaming "master" to "main" #BLM

### ISSUE THREAD

**Issue by anishkny** [MarkLodato/visual-git-guide#66]
Some context: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

Edit: I wanted to say this is an **excellent** guide - succinct, clear, thorough - kudos! Would love to see it made more inclusive and have a lesser chance of evoking possibly painful memories.

**Comment by memowe** [comment]
This is actually a very good idea and easy to realize with a huge find-and-replace, followed by a pull request.
