### ISSUE TITLE
Wrong link to website in about section

### ISSUE THREAD

**Issue by basejumpa** [MarkLodato/visual-git-guide#71]
At https://github.com/MarkLodato/visual-git-guide on the right in the **about** section the link to the website is wrong and therefore broken. `.com` needs to changed to `.io`.

**Comment by MarkLodato** [comment]
Are you sure? That link appears to be working fine. To be clear, `github.com/<user>/<repo>` is a link to GitHub repository, while `<user>.github.io/<repo>` is a link to a rendered GitHub Pages site.

That said, I fixed the Japanese version which used the wrong domain.
